import { describe, expect, it } from 'vitest';

import { serializePublishedMarkdown } from './published-markdown.js';

/*
 * A synthetic marker: the real one names a deployment, and this package has no
 * deployment of its own.
 */
const marker = '<!-- AUTO-GENERATED BY EXAMPLE SYNC. DO NOT EDIT. -->';

function input(body: string) {
  return {
    title: 'Guide [safe]',
    sourceUrl: 'https://docs.google.com/document/d/source/edit',
    googleModifiedTime: '2026-07-30T12:00:00.000Z',
    syncedAt: '2026-07-31T12:00:00.000Z',
    contentHash: `sha256:${'a'.repeat(64)}`,
    body: `${marker}\n\n${body}`,
    ownershipHeader: marker,
    stableSlugs: new Set(['section/target']),
  };
}

describe('published Markdown', () => {
  it('serializes selected metadata and an explicit title', () => {
    const result = serializePublishedMarkdown(input('Document body.'));

    expect(result).toContain('title: "Guide [safe]"');
    expect(result).toContain('# Guide \\[safe\\]');
    expect(result).toContain('Document body.');
    expect(result).not.toContain('AUTO-GENERATED');
    expect(result).not.toContain('googleFileId');
    expect(result.endsWith('\n')).toBe(true);
  });

  it('rewrites Markdown and HTML links to published Markdown routes', () => {
    const result = serializePublishedMarkdown(
      input(
        '[Markdown target](/section/target/#heading)\n\n' +
          '<a href="/section/target/">HTML target</a>\n\n' +
          '[External](https://example.com)',
      ),
    );

    expect(result).toContain('/section/target/index.md#heading');
    expect(result).toContain('href="/section/target/index.md"');
    expect(result).toContain('https://example.com');
  });

  it('preserves generated asset references', () => {
    const result = serializePublishedMarkdown(
      input('![Diagram](../../../assets/generated/doc/image-001.png)'),
    );

    expect(result).toContain(
      '![Diagram](../../../assets/generated/doc/image-001.png)',
    );
  });

  it('rejects content without the generated ownership marker', () => {
    expect(() =>
      serializePublishedMarkdown({ ...input('body'), body: 'body' }),
    ).toThrow('ownership marker');
  });

  it('supports an empty generated document', () => {
    const result = serializePublishedMarkdown({
      ...input(''),
      body: marker,
    });

    expect(result).toContain('# Guide \\[safe\\]');
    expect(result.endsWith('\n')).toBe(true);
  });
});
