import {
  publishedMarkdownBody,
  serializePublishedMarkdown,
} from '@ctcstack/ctcdocs-core/published-markdown';
import { describe, expect, it } from 'vitest';

import { documentText } from './document-text.js';

const marker = '<!-- AUTO-GENERATED BY EXAMPLE SYNC. DO NOT EDIT. -->';

function input(title: string, body: string, fileUrl?: string) {
  return {
    title,
    sourceUrl: 'https://docs.google.com/document/d/source/edit',
    ...(fileUrl ? { fileUrl } : {}),
    googleModifiedTime: '2026-07-30T12:00:00.000Z',
    syncedAt: '2026-07-31T12:00:00.000Z',
    contentHash: `sha256:${'a'.repeat(64)}`,
    body: `${marker}\n\n${body}`,
    ownershipHeader: marker,
    stableSlugs: new Set<string>(),
    permanentLinks: {},
  };
}

describe('the text the MCP server keeps', () => {
  it.each([
    ['a plain document', input('Guide', 'Body text.')],
    ['an empty document', input('Empty', '')],
    ['a title that reads as front matter', input('---\n---', 'Body.')],
    [
      'a rule and a fenced block of dashes',
      input('Rules', 'Above.\n\n---\n\n```yaml\n---\nkey: value\n---\n```'),
    ],
    [
      'a published PDF',
      input('Scan', 'Page text.', '/assets/generated/pdf/file.pdf'),
    ],
  ])('is the body of %s, without its front matter', (_label, value) => {
    const text = documentText(serializePublishedMarkdown(value));
    expect(text).toBe(publishedMarkdownBody(value));
    expect(text).not.toContain('synced_at');
    expect(text).not.toContain('content_hash');
  });

  it('closes an empty front matter', () => {
    expect(documentText('---\n---\n\n# Title\n')).toBe('# Title\n');
  });

  it.each([
    ['no front matter', '# Title\n\nBody.\n'],
    ['a front matter never closed', '---\ntitle: "x"\n# Title\n'],
    ['an empty file', ''],
  ])('finds nothing in %s', (_label, projection) => {
    expect(documentText(projection)).toBe(undefined);
  });
});
