import type { SiteConfiguration } from './site-configuration.js';

/**
 * Ownership markers, derived from `sync.generatedBy` in the project
 * configuration so one setting names the pipeline everywhere it signs its
 * output. Markdown carries the HTML-comment form; generated TypeScript carries
 * the line-comment form.
 *
 * They are functions of the configuration rather than constants because the
 * platform does not own the value: it is read from the project that installed
 * the platform, and two projects sharing this package must not share a marker.
 */
export function generatedMarkdownHeader(
  configuration: SiteConfiguration,
): string {
  return `<!-- AUTO-GENERATED BY ${configuration.sync.generatedBy}. DO NOT EDIT. -->`;
}

export function generatedSourceHeader(
  configuration: SiteConfiguration,
): string {
  return `// AUTO-GENERATED BY ${configuration.sync.generatedBy}. DO NOT EDIT.`;
}
