import { describe, expect, it } from 'vitest';

import {
  publishedMarkdownBody,
  serializePublishedMarkdown,
} from './published-markdown.js';

/*
 * A synthetic marker: the real one names a deployment, and this package has no
 * deployment of its own.
 */
const marker = '<!-- AUTO-GENERATED BY EXAMPLE SYNC. DO NOT EDIT. -->';

function input(body: string) {
  return {
    title: 'Guide [safe]',
    sourceUrl: 'https://docs.google.com/document/d/source/edit',
    googleModifiedTime: '2026-07-30T12:00:00.000Z',
    syncedAt: '2026-07-31T12:00:00.000Z',
    contentHash: `sha256:${'a'.repeat(64)}`,
    body: `${marker}\n\n${body}`,
    ownershipHeader: marker,
    stableSlugs: new Set(['section/target']),
    permanentLinks: {
      '/d/a1b2c3/': '/section/target/',
      '/d/0f0f0f/': '/section/',
    },
  };
}

describe('published Markdown', () => {
  it('serializes selected metadata and an explicit title', () => {
    const result = serializePublishedMarkdown(input('Document body.'));

    expect(result).toContain('title: "Guide [safe]"');
    expect(result).toContain('# Guide \\[safe\\]');
    expect(result).toContain('Document body.');
    expect(result).not.toContain('AUTO-GENERATED');
    expect(result).not.toContain('googleFileId');
    expect(result.endsWith('\n')).toBe(true);
  });

  it('rewrites Markdown and HTML links to published Markdown routes', () => {
    const result = serializePublishedMarkdown(
      input(
        '[Markdown target](/section/target/#heading)\n\n' +
          '<a href="/section/target/">HTML target</a>\n\n' +
          '[External](https://example.com)',
      ),
    );

    expect(result).toContain('/section/target/index.md#heading');
    expect(result).toContain('href="/section/target/index.md"');
    expect(result).toContain('https://example.com');
  });

  it('names the Markdown of the page a permanent link leads to', () => {
    const result = serializePublishedMarkdown(
      input(
        '[Document](/d/a1b2c3/#heading)\n\n' +
          '<a href="/d/a1b2c3/">HTML document</a>\n\n' +
          '[Section](/d/0f0f0f/)\n\n' +
          '[Unknown](/d/ffffff/)',
      ),
    );

    expect(result).toContain('(/section/target/index.md#heading)');
    expect(result).toContain('href="/section/target/index.md"');
    // A section has no Markdown projection; its page is the destination.
    expect(result).toContain('[Section](/section/)');
    expect(result).toContain('[Unknown](/d/ffffff/)');
  });

  it('preserves generated asset references', () => {
    const result = serializePublishedMarkdown(
      input('![Diagram](../../../assets/generated/doc/image-001.png)'),
    );

    expect(result).toContain(
      '![Diagram](../../../assets/generated/doc/image-001.png)',
    );
  });

  it('rejects content without the generated ownership marker', () => {
    expect(() =>
      serializePublishedMarkdown({ ...input('body'), body: 'body' }),
    ).toThrow('ownership marker');
  });

  it('supports an empty generated document', () => {
    const result = serializePublishedMarkdown({
      ...input(''),
      body: marker,
    });

    expect(result).toContain('# Guide \\[safe\\]');
    expect(result.endsWith('\n')).toBe(true);
  });

  it('ends with the body the MCP server keeps, after the front matter', () => {
    for (const body of ['Document body.\n\n---\n\nAfter a rule.', '']) {
      const value = input(body);
      const whole = serializePublishedMarkdown(value);
      const kept = publishedMarkdownBody(value);

      expect(kept).toBe(
        body
          ? `# Guide \\[safe\\]\n\n${body.replace('---', '***')}\n`
          : '# Guide \\[safe\\]\n',
      );
      expect(whole.endsWith(`---\n\n${kept}`)).toBe(true);
      expect(kept).not.toContain('source_url');
    }
  });

  it('writes tables without padding', () => {
    const result = publishedMarkdownBody(
      input('| Name | Note |\n| --- | --- |\n| A | A much longer note |\n'),
    );

    expect(result).toContain(
      '| Name | Note |\n| - | - |\n| A | A much longer note |',
    );
  });

  it('splits a long table into parts that repeat its header', () => {
    const rows = Array.from(
      { length: 120 },
      (_, index) => `| Row ${index + 1} | ${'x'.repeat(40)} |`,
    );
    const result = publishedMarkdownBody(
      input(['| Item | Detail |', '| --- | ---: |', ...rows].join('\n')),
    );

    const parts = result.split('| Item | Detail |\n| - | -: |\n');
    // The title before the first table, then one entry per part.
    expect(parts.length).toBeGreaterThan(3);
    for (const part of parts.slice(1)) {
      expect(part.length).toBeLessThan(2_200);
    }
    for (const row of rows) {
      expect(result).toContain(row);
    }
    expect(result.indexOf('| Row 1 |')).toBeLessThan(
      result.indexOf('| Row 120 |'),
    );
  });

  it('keeps a table that fits whole', () => {
    const result = publishedMarkdownBody(
      input('| Item |\n| --- |\n| One |\n| Two |\n'),
    );

    expect(result.match(/\| Item \|/gu)).toHaveLength(1);
  });
});
